version: '3.4'

services:
  catalogservice.mongo:
    container_name: catalogservice.mongo
    restart: always
    volumes:
        - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
        - "27018:27017"
  
  basketservice.redis:
    container_name: basketservice.redis
    restart: always
    ports:
        - "6379:6379"
  
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"

  catalogservice.api:
    container_name: catalogservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CatalogDbSettings:ConnectionString=mongodb://catalogservice.mongo:27018"
    depends_on:
      - catalogservice.mongo
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/
    ports:
      - "8000:80"

  basketservice.api:
    container_name: basketservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:Redis=basketservice.redis:6379"
      - "EventBus:HostName=rabbitmq"
    depends_on:
      - basketservice.redis
      - rabbitmq
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/
    ports:
      - "8001:80"

