version: '3.4'

services:
  catalogservice.mongo:
    image: mongo

  basketservice.redis:
    image: redis

  rabbitmq:
    image: rabbitmq:3-management-alpine

  catalogservice.api:
    image: ${DOCKER_REGISTRY-}catalogserviceapi
    build:
      context: .
      dockerfile: src/CatalogService/CatalogService.API/Dockerfile

  basketservice.api:
    image: ${DOCKER_REGISTRY-}basketserviceapi
    build:
      context: .
      dockerfile: src/BasketService/BasketService.API/Dockerfile

